---
# tasks file for haproxy

- name: Install haproxy
  apt:
    name: haproxy
    update_cache: yes
    state: latest

- name: Ajout de la Configuration
  template:
    src: haproxy_config.yml.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy
