---
# handlers file for commonk8s
- name: restart kubelet
  service:
    name: kubelet
    state: restarted
    daemon_reload: yes

- name: docker status
  service:
    name: docker
    state: started

- name: docker restart
  service:
    name: docker
    state: restarted
