---
# tasks file for commonk8s
- name: clean older docker version
  apt:
    name: "{{ item }}"
    state: absent
  with_items: "{{ docker_remove }}"

- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ https_packages }}"

- name: Add new repositories keys
  apt_key:
    url: "{{ item.key }}"
    state: present
  with_items: "{{ gpg_keys | default([]) }}"

- name: Add new apt repositories
  apt_repository:
    repo: "{{ item.repo }}"
    state: present
  with_items: "{{ repositories | default([]) }}"

- name: Install docker
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ docker_packages }}"
  notify: docker status
